### ISSUE TITLE
advanced-cache.php generate

### ISSUE THREAD

**Issue by Kostetikus** [sanderdekroon/WP-Rocket-Guest-Cache#1]
Hi.

I really need this solution! My site with WP-Rocket works really well for unlogged users and slow for logged in users. 
I installed your plugin, but it didn't work as needed. 
I deleted file advanced-cache.php as written, but the WP-Rocket did not create a new file advanced-cache.php.
Can you please tell me what I need to do for the WP-Rocket to create a new advanced-cache.php?
Do I need to create a new preload cache after installing your plugin?

**Comment by sanderdekroon** [comment]
It should generate a new one by visiting the WP-Rocket settings page. Could you try that?

**Comment by Kostetikus** [comment]
Thanks for the quick response.
Yes. It worked. A new file advanced-cache.php was created.
But the non-cached pages are still loaded for the logged in users.

**Comment by sanderdekroon** [comment]
Please check if the `advanced-cache.php` file contains the `SdkGuestCache` class. If it doesn't, you are probably missing the required helpers. 

If it does, please make sure that the the pages you are viewing are actually cached.

Usually I first view the page in a new private/incognito window. This way I'm not logged in and I can verify that the page is actually cached by viewing the page source. Then I will log myself in and view the same page yet again. It _should_ then serve the page from the guest cache.

**Comment by Kostetikus** [comment]
Thank you for your reply.

My new advanced-cache.php file contains the SdkGuestCache class. 


> class SdkGuestCache extends \WP_Rocket\Buffer\Cache
            {
                protected $sdkConfig;

                public function __construct(
                    \WP_Rocket\Buffer\Tests $tests,
                    \WP_Rocket\Buffer\Config $config,
                    array $args
                ) {
                    parent::__construct($tests, $config, $args);
                    $this->sdkConfig = $config;
                }

                public function get_cache_path($args = [])
                {
                    $path = parent::get_cache_path($args);

                    if (strpos($path, "-loggedin-") === false) {
                        return $path;
                    }

                    return str_replace(
                        "-loggedin-" . $this->sdkConfig->get_config("secret_cache_key"),
                        "",
                        $path
                    );
                }
            }

>( new SdkGuestCache(
  new Tests(
    $rocket_config_class
  ),
  $rocket_config_class,
  [
    'cache_dir_path' => $rocket_cache_path,
  ]
) )->maybe_init_process();

> 



> Usually I first view the page in a new private/incognito window. This way I'm not logged in and I can verify that the page is actually cached by viewing the page source. Then I will log myself in and view the same page yet again. It _should_ then serve the page from the guest cache.

I do the same.
For an unlogged user, all pages source contain the last line: 
"... Performance optimized by WP Rocket...."

And, for example, in  pages source I can see the link:
.../wp-content/cache/min/1/***.css

After log in, the guest cached home page opens.
After the first click on any link, the guest cached page opens.
From the second click, non-cached pages open for the logged in user.
From the second click, for a logged in user all pages do not contain last line
"... Performance optimized by WP Rocket...."

And no link to the cache
.../wp-content/cache/min/1/***.css

**Comment by sanderdekroon** [comment]
Could you maybe send the URL to the website you are working on? Does it have open registration, so I can test for myself?

I'm guessing it has to do with the `str_replace()` call. Perhaps the 'secret_cache_key' from the config is somehow not in the cache path. Could you perhaps replace `str_replace` with this call: `return preg_replace('/(-loggedin-[\w-]+)/', '', $path);` ?

**Comment by Kostetikus** [comment]
https://suns.lv/
The plugin "WP Rocket Guest Cache" is currently deactivated.
The plugins "WP Rocket | Common Cache For Logged-in Users", "WP Rocket | No Cache for Admins" are activated.
I can activate  "WP Rocket Guest Cache" if need to.

> Could you perhaps replace `str_replace` with this call: `return preg_replace('/(-loggedin-[\w-]+)/', '', $path);` ?

Please tell me in which file I should replace `str_replace`

**Comment by sanderdekroon** [comment]
In `advanced-cache.php` :)
