### ISSUE TITLE
logged-in cache is still generated

### ISSUE THREAD

**Issue by dk-fbeckmann** [sanderdekroon/WP-Rocket-Guest-Cache#10]
First of all, I think your approach that everyone gets the logged-out cache is very good. We have an online shop with several thousand products, of which at least 500 products are updated every day and their cache has to be emptied accordingly. For those who are logged in, this means that they almost never call up a cached page. The same naturally applies to the product categories, whose cache almost never lasts longer than a few minutes due to the many necessary updates. That's a problem for people who aren't logged in, but it's even worse for people who are logged in, which is why I really want to continue testing your plugin. Although we have specific content for those who are logged in, we load this separate information later anyway via javascript. So all users can get the same cached version.

But now I noticed that despite the activated plugins, a logged-in cache version is created. Even if there is already a non-logged-in cache version for the post. The process of generating the cache for those who are logged in again means that the page call takes significantly longer.

Probably it is the same problem mentioned in https://github.com/sanderdekroon/WP-Rocket-Guest-Cache/issues/9

Do you see a way to completely disable the creation of logged-in cache files?

Thank you for the help!

**Comment by sanderdekroon** [comment]
@dk-fbeckmann I'm closing this issue in favor of #9. Let's continue there.
