### ISSUE TITLE
Cache is being served to logged in admins

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [sanderdekroon/WP-Rocket-Guest-Cache#14]
Hi @sanderdekroon 

This plugin is no longer functioning properly.

On the two sites we have implimented this on - Admins are being served the same cache as non admins.

Therefore admins dont have the bar at the top of the screen.

We have all of the helper plugins installed.

Any ideas why this could happen? Happy to share the website addresses with you if you are able to help us.

**Comment by thinkjarvisdesignandmarketing** [comment]
![image](https://github.com/user-attachments/assets/e33d976f-16dd-4a37-9fa5-a3c21d37130b)

This plugin stack no longer works properly due to this.

**Comment by MikeAMAWork** [comment]
I’m pretty sure that’s how it is supposed to work. It’s always worked that way. If the page is in the cache it serves the cached page.

**Comment by sanderdekroon** [comment]
This is how the plugin is supposed to work. The plugin will make WP Rocket serve the guest cache to everyone, even logged-in users. Admins are logged-in users and will therefore see the guest page cache. 

If you want admins to see the bar at the top _and_ serve a cached page to them, this plugin is not for you. You can make that work with the default functionality of WP Rocket. But beware: WP Rocket will make a page cache per user. In my experience, this doesn't speed up things very much.

**Comment by thinkjarvisdesignandmarketing** [comment]
Thanks @sanderdekroon for confirming.

I had assumed that because we were using the no cache for admins plugin that it isnt supposed to serve the cache to them. Seems like an odd decision by WP-Rocket to not add an exception into the helper plugins so they are fully compatible with eachother. Seems like expected behaviour in my oppinion.

I understand now it basically means if you enable the user cache it doesnt serve them to admin NOT dont serve cache to admins.

Makes sense now thank you.

We are looking at building a custom plugin that dynamically grabs the stock values for products so that we can perminently cache the site for all visitors, both signed in and signed out.

**Comment by sanderdekroon** [comment]
Great to hear that. I realize it's hard to explain what this plugin does and doesn't do. Especially with the type of helpers you need to install. I'll look into updating the readme page to make this more clear.
