### ISSUE TITLE
Admin Users No-Cache

### ISSUE THREAD

**Issue by mr-sparks** [sanderdekroon/WP-Rocket-Guest-Cache#3]
Hi there,

is the only reason to use the Admin No-Cache Add-on the possibility of the admin bars showing? Meaning: If I edit every admin user and make sure they don't have the admin-bar activated, could I then skip the Admin User's No-Cache Add-On, so that only Admin-Users see a non-cached version of the site?

Thanks a lot!

**Comment by sanderdekroon** [comment]
Sorry for the late reply. But yes: the only reason the add-on is 'required', is to make sure no admin bars are showing. Ever.

But if you would deactivate the adminbar for every admin, then I _think_ the addon would not be required. I haven't tested that use case, you YMMV.
