### ISSUE TITLE
Critical Error When Activated

### ISSUE THREAD

**Issue by MikeAMAWork** [sanderdekroon/WP-Rocket-Guest-Cache#5]
I installed the plug-in, but when I activate it, I get a critical error on the site.  Any ideas?

**Comment by MikeAMAWork** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined function Sanderdekroon\WPRocket\is_plugin_active() in /home/vjghcfj/public_html/wp-content/plugins/WP-Rocket-Guest-Cache-main/wp-rocket-guest-cache.php:72

**Comment by sanderdekroon** [comment]
I've pushed an update which should fix this issue.
