### ISSUE TITLE
Exclude "admins" from seeing cache if they use static IP addresses

### ISSUE THREAD

**Issue by trendymail** [sanderdekroon/WP-Rocket-Guest-Cache#6]
Hello from France!

Long story short:

1) Your plugin is insanely awesome :)
2) I understand how difficult it is to exclude "admins" in advanced-cache.php

---

But, if "admins" are using a static IP adress, it shoud be easy to exclude them.

I know, this it is a quick and dirty hack.

But it would be simple to implement (I will give a shot in a few days).

=> $_SERVER['REMOTE_ADDR'] and $_SERVER['HTTP_X_FORWARDED_FOR']

---

I am not a WordPress expert but, how much time would be required to manually load every WordPress files needed to call "is_admin()" function?

However, even if it is possible, it might slow down TTFB.

Have a great night. :)

**Comment by sanderdekroon** [comment]
I don't have the time right now to implement such a feature. If you want, you are free to submit a PR.
